// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
}


// Validate ..\..\src\app\(site)\blog\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(site)\\blog\\page.js")
  handler satisfies AppPageConfig<"/blog">
}

// Validate ..\..\src\app\(site)\blog\praktische-tips-voor-ondernemers\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(site)\\blog\\praktische-tips-voor-ondernemers\\page.js")
  handler satisfies AppPageConfig<"/blog/praktische-tips-voor-ondernemers">
}

// Validate ..\..\src\app\(site)\contact\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(site)\\contact\\page.js")
  handler satisfies AppPageConfig<"/contact">
}

// Validate ..\..\src\app\(site)\diensten\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(site)\\diensten\\page.js")
  handler satisfies AppPageConfig<"/diensten">
}

// Validate ..\..\src\app\(site)\over-mij\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(site)\\over-mij\\page.js")
  handler satisfies AppPageConfig<"/over-mij">
}

// Validate ..\..\src\app\(site)\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(site)\\page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ..\..\src\app\(site)\portfolio\[slug]\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(site)\\portfolio\\[slug]\\page.js")
  handler satisfies AppPageConfig<"/portfolio/[slug]">
}

// Validate ..\..\src\app\(site)\portfolio\boekhouder-nl\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(site)\\portfolio\\boekhouder-nl\\page.js")
  handler satisfies AppPageConfig<"/portfolio/boekhouder-nl">
}

// Validate ..\..\src\app\(site)\portfolio\coach-online\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(site)\\portfolio\\coach-online\\page.js")
  handler satisfies AppPageConfig<"/portfolio/coach-online">
}

// Validate ..\..\src\app\(site)\portfolio\fysio-praktijk\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(site)\\portfolio\\fysio-praktijk\\page.js")
  handler satisfies AppPageConfig<"/portfolio/fysio-praktijk">
}

// Validate ..\..\src\app\(site)\portfolio\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(site)\\portfolio\\page.js")
  handler satisfies AppPageConfig<"/portfolio">
}

// Validate ..\..\src\app\(site)\portfolio\salon-studio\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(site)\\portfolio\\salon-studio\\page.js")
  handler satisfies AppPageConfig<"/portfolio/salon-studio">
}

// Validate ..\..\src\app\api\contact\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\contact\\route.js")
  handler satisfies RouteHandlerConfig<"/api/contact">
}





// Validate ..\..\src\app\(site)\layout.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(site)\\layout.js")
  handler satisfies LayoutConfig<"/">
}

// Validate ..\..\src\app\layout.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\layout.js")
  handler satisfies LayoutConfig<"/">
}
